name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [20, 17, 11, 8]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_java_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.5.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: sbt test
